PLUGIN_NAME=		goddy
PLUGIN_VERSION=		0.5.3-dev
PLUGIN_REVISION=	2
PLUGIN_COMMENT=		Dynamic DNS Support for GoDaddy service
PLUGIN_MAINTAINER=	opwallin@gmail.com
PLUGIN_DEPENDS=		sqlite3 php${PLUGIN_PHP}-sqlite3


.include "../../Mk/plugins.mk"
