PLUGIN_NAME=		goddy
PLUGIN_VERSION=		0.6.14
PLUGIN_REVISION=	1
PLUGIN_COMMENT=		Dynamic DNS Support for GoDaddy service
PLUGIN_MAINTAINER=	opwallin@gmail.com
PLUGIN_DEPENDS=


.include "../../Mk/plugins.mk"
