PLUGIN_NAME=		dyndnsgd
PLUGIN_VERSION=		0.4.0-dev
PLUGIN_REVISION=	3
PLUGIN_COMMENT=		Dynamic DNS Support for GoDaddy service
PLUGIN_MAINTAINER=	opwallin@gmail.com
PLUGIN_DEPENDS=		sqlite3 php${PLUGIN_PHP}-sqlite3


.include "../../Mk/plugins.mk"
